{% set name = "pyGLFW" %}
{% set version = "2.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FlorianRhiem/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0c8570a683c866c8427c52f6d11311d4e7423df1f7e2f9e583186effbd97e373

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - glfw

test:
  imports:
    - glfw
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/FlorianRhiem/pyGLFW
  summary: This module provides Python bindings for GLFW
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: This module provides Python bindings for GLFW
  doc_url: https://github.com/FlorianRhiem/pyGLFW
  dev_url: https://github.com/FlorianRhiem/pyGLFW

extra:
  recipe-maintainers:
    - hoechenberger
    - kastman
